**If you use Google Colab, you can uncomment the following cells to mount Google drive to Colab, and change the working directory to your Colab Notebook folder in your Google drive.**

In [1]:
# mount your google drive with Colab

#from google.colab import drive
#drive.mount('/content/drive')


In [2]:
# change the working directory to your folder in Google Drive. I have a folder "Colab Notebooks" in my Stony Brook Google Drive
#%cd /content/drive/MyDrive/Colab Notebooks

In [3]:
# check contents in the current directory
#!ls

**Notebook setting**

In [4]:
# Display all outputs from each cell

from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"



**Import libraries and packages that would be used in this notebook**

In [5]:
# call libraries that will be used
import numpy as np      # Low-level numerical Python library. https://numpy.org/

## Scalars, Vectors, and Matrices

### Scalars

In [6]:
# define a scalar
x = np.array(0.5)

x

array(0.5)

### Vectors

In [7]:
# define a row vector

x = np.array([1., 3., 4.])
x

array([1., 3., 4.])

In [8]:
# define a colum vector

x = np.array([[1.],
     [3.],
     [4.]])
x

array([[1.],
       [3.],
       [4.]])

### Matrices

In [9]:
# define matrix by reshaping a vector

A = np.arange(1.,13.).reshape(2,3,2)
A

array([[[ 1.,  2.],
        [ 3.,  4.],
        [ 5.,  6.]],

       [[ 7.,  8.],
        [ 9., 10.],
        [11., 12.]]])

In [10]:
# define a matrix directly by specifying matrix element by element

A=np.matrix('[1.,2.,3.;4.,5.,6.]')
A

matrix([[1., 2., 3.],
        [4., 5., 6.]])

In [11]:
# define a matrix by delineating row by row
A = np.matrix([[1., 2.],
              [3., 4.],
              [5., 6.]])
A

matrix([[1., 2.],
        [3., 4.],
        [5., 6.]])

## Operations

### Transpose

In [12]:
A = np.arange(1.,7.).reshape(2,3)
print(f'A=\n{A}\n')

A_T = np.transpose(A) # np.transpose()
print(f'The transpose of A, A^T=\n {A_T} \n')

A=
[[1. 2. 3.]
 [4. 5. 6.]]

The transpose of A, A^T=
 [[1. 4.]
 [2. 5.]
 [3. 6.]] 



### Addition & Subtraction

In [13]:
A = np.arange(1.,7.).reshape(3,2)
print(f'A=\n {A} \n')

B = np.arange(7.,13.).reshape(3,2)
print(f'B=\n {B} \n')

d= np.arange(10.,13.).reshape(3,1)
print(f'd=\n {d} \n')

print(f'A+B=\n {A+B} \n')

print(f'2*A+3=\n {2*A+3} \n')

print(f'A+d=\n {A+d} \n')

print(f'A-B=\n {A-B} \n')


A=
 [[1. 2.]
 [3. 4.]
 [5. 6.]] 

B=
 [[ 7.  8.]
 [ 9. 10.]
 [11. 12.]] 

d=
 [[10.]
 [11.]
 [12.]] 

A+B=
 [[ 8. 10.]
 [12. 14.]
 [16. 18.]] 

2*A+3=
 [[ 5.  7.]
 [ 9. 11.]
 [13. 15.]] 

A+d=
 [[11. 12.]
 [14. 15.]
 [17. 18.]] 

A-B=
 [[-6. -6.]
 [-6. -6.]
 [-6. -6.]] 



### Multiplication

In [14]:
A = np.arange(1.,7.).reshape(3,2)
print(f'A=\n {A,}, \n')

B = np.arange(7.,13.).reshape(3,2)
print(f'B=\n {B} \n')

c = np.arange(4.,6.)
print(f'c=\n {c} \n')

d = np.arange(1.,4.)
print(f'd=\n {d} \n')

E = np.arange(1.,7.).reshape(2,3)
print(f'E=\n {E} \n')

# Hadamard product (element-wise product)
print(f'A*B=\n {A*B} \n')

# matrix multiplication (using np.matmul)
print(f'dA=\n {np.matmul(d,A)} \n')

print(f'EA=\n {np.matmul(E,A)} \n')

print(f'Ac^T= {np.matmul(A,np.transpose(c))} \n')

A=
 (array([[1., 2.],
       [3., 4.],
       [5., 6.]]),), 

B=
 [[ 7.  8.]
 [ 9. 10.]
 [11. 12.]] 

c=
 [4. 5.] 

d=
 [1. 2. 3.] 

E=
 [[1. 2. 3.]
 [4. 5. 6.]] 

A*B=
 [[ 7. 16.]
 [27. 40.]
 [55. 72.]] 

dA=
 [22. 28.] 

EA=
 [[22. 28.]
 [49. 64.]] 

Ac^T= [14. 32. 50.] 



### Matrix Diagonal

In [15]:
A = np.arange(1.,17.).reshape(4,4)
print(f'A=\n {A} \n')

A_diag=np.diag(A) # find the diagnal of the matrix using np.diag()
print(f'Diagonal values of A:\n {A_diag}')

A=
 [[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]
 [13. 14. 15. 16.]] 

Diagonal values of A:
 [ 1.  6. 11. 16.]


### Matrix Transpose

In [16]:
A = np.arange(1.,7.).reshape(2,3)
print(f'A=\n {A} \n')

A_T=np.transpose(A)
print(f'The transpose of A, A_T=\n {A_T} \n')

A=
 [[1. 2. 3.]
 [4. 5. 6.]] 

The transpose of A, A_T=
 [[1. 4.]
 [2. 5.]
 [3. 6.]] 



### Identity Matrix and Inverse Operator

In [17]:
a = np.arange(2.,5.)
print(f'a=\n {a} \n')

I = np.eye(3)
print(f'I=\n {I} \n')

print(f'aI=\n {np.matmul(a,I)} \n') # check if aI does not change the vector a

print(f'Ia=\n {np.matmul(I,np.transpose(a))}') # check if Ia does not change a

a=
 [2. 3. 4.] 

I=
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 

aI=
 [2. 3. 4.] 

Ia=
 [2. 3. 4.]


In [18]:
# Inverse of a matrix
A = np.arange(1.,5.).reshape(2,2)
print(f'A=\n {A} \n')

A_inv=np.linalg.inv(A) # find the inverse of a matrix using np.linalg.inv
print(f'The inverse of A is, \n {A_inv} \n')

print(f'A multiplied by its inverse matrix, AA_inv, is the identify matrix:\n {np.matmul(A,A_inv)} \n') # the multiplication of A and A's inverse is an identical matrix


A=
 [[1. 2.]
 [3. 4.]] 

The inverse of A is, 
 [[-2.   1. ]
 [ 1.5 -0.5]] 

A multiplied by its inverse matrix, AA_inv, is the identify matrix:
 [[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]] 



### Trace

In [19]:
A = np.arange(1.,10.).reshape(3,3)
print(f'A=\n {A} \n')

A_trace = np.trace(A) # np.trace() is the function for finding the trace of a matrix
print(f'The trace of A is: \n {A_trace}') # check if A_trace is the summation of elements on the diagnal

A=
 [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]] 

The trace of A is: 
 15.0


### Determinant

In [20]:
A=np.arange(1.,5.).reshape(2,2)
print(f'A:\n {A} \n')

A_det=np.linalg.det(A) # find the determinant of a matrix using np.linalg.det
print(f'determinant of A:\n {A_det:.2f}')

A:
 [[1. 2.]
 [3. 4.]] 

determinant of A:
 -2.00


## Norms

### $l_1$-Norm

In [21]:
A=np.arange(-2.,2.)
print(f'A:\n {A} \n')

A_norm1=np.linalg.norm(A,ord=1) #np.linalg.norm(tensor, ord=) computes the norm of a tensor
print(f'L_1 norm of A:\n {A_norm1:.2f}')

A:
 [-2. -1.  0.  1.] 

L_1 norm of A:
 4.00


### $l_2$-Norm

In [22]:
A=np.arange(-2.,2.)
print(f'A:\n {A} \n')

A_norm2=np.linalg.norm(A,ord=2)
print(f'L_2 norm of A:\n {A_norm2:.2f}')

A:
 [-2. -1.  0.  1.] 

L_2 norm of A:
 2.45


### $l_\infty$-Norm

In [23]:
A=np.arange(-2.,2.)
print(f'A:\n {A} \n')

A_norminf=np.linalg.norm(A,ord=np.inf)
print(f'L_inf norm of A:\n {A_norminf:.2f}')

A:
 [-2. -1.  0.  1.] 

L_inf norm of A:
 2.00


### Frobenius Norm

In [24]:
A=np.arange(-2.,2.).reshape(2,2)
print(f'A:\n {A} \n')

A_Fro=np.linalg.norm(A,ord='fro')
print(f'Frobenius norm of A:\n {A_Fro:.2f}')

A:
 [[-2. -1.]
 [ 0.  1.]] 

Frobenius norm of A:
 2.45


## Decompositions

### Eigen Decomposition

In [25]:
A = np.array([5.,1.,3.,3.]).reshape(2,2)
print(f'A:\n {A} \n')

e,V=np.linalg.eig(A)# find eigenvalues and eigenvectors of a matrix using np.linalg.eig()
print(f'eigenvalues of A:\n e = {e}')

print(f'eigenvectors of A: \n V = {V} \n')

L=(np.diag(e)) #construct the eighen value matrix using np.diag()
print(f'Eigenvalue matrix:\n {L} \n')

print(f'EigenDecomposition of A:\n {abs(np.matmul(np.matmul(V,L),np.linalg.inv(V)))-A} \n') # check if A is equal to its eigendecomposition VLV^(-1)


print(f'det(A)-the product of eigenvalues:\n {np.linalg.det(A)-np.prod(e):.3f} \n') # check if the determinant of A is equal to the product of A's eigenvalues


A:
 [[5. 1.]
 [3. 3.]] 

eigenvalues of A:
 e = [6. 2.]
eigenvectors of A: 
 V = [[ 0.70710678 -0.31622777]
 [ 0.70710678  0.9486833 ]] 

Eigenvalue matrix:
 [[6. 0.]
 [0. 2.]] 

EigenDecomposition of A:
 [[ 0.0000000e+00  0.0000000e+00]
 [-4.4408921e-16  4.4408921e-16]] 

det(A)-the product of eigenvalues:
 -0.000 



### Singular Value Decomposition

In [26]:
A = np.random.randn(2,3)
print(f'A:\n {A} \n')

U,D,V = np.linalg.svd(A, full_matrices=False) # singular value decomposition using np.linalg.svd()
print(f'left singular vectors, U:\n {U} \n')
print(f'singular values, D:\n {D} \n')
print(f'right singular vectors, V:\n {V} \n')

np.transpose(V)
#np.matmul(np.matmul(U,np.diag(D)),np.transpose(V))

print(f'UDV-A:\n {np.matmul(np.matmul(U,np.diag(D)), V)-A}') # let's check if UDV is approximately equal to A

A:
 [[ 0.644441    0.64385957 -0.2121843 ]
 [-0.35356771  1.6615368  -1.36311934]] 

left singular vectors, U:
 [[-0.26148938 -0.96520635]
 [-0.96520635  0.26148938]] 

singular values, D:
 [2.24727879 0.75394202] 

right singular vectors, V:
 [[ 0.07687133 -0.7885485   0.61014922]
 [-0.94764947 -0.24800729 -0.201129  ]] 



array([[ 0.07687133, -0.94764947],
       [-0.7885485 , -0.24800729],
       [ 0.61014922, -0.201129  ]])

UDV-A:
 [[-1.11022302e-16 -1.11022302e-16  0.00000000e+00]
 [-2.22044605e-16  0.00000000e+00  0.00000000e+00]]


In [27]:
# Let's check if the left-singular vectors of A are the eigenvectors of AA^T and if the square root of the non-zero eigenvalues of AA^T are the singular values of A
L,V=np.linalg.eig(np.matmul(A, np.transpose(A)))

print(f'eighenvectors of AA^T:\n {V} \n')

print(f'square root of nonzero eigenvalues of AA^T:\n {np.sqrt(L)} \n')

eighenvectors of AA^T:
 [[-0.96520635 -0.26148938]
 [ 0.26148938 -0.96520635]] 

square root of nonzero eigenvalues of AA^T:
 [0.75394202 2.24727879] 



In [28]:
# Let's check if the right-singular vectors of A are the eigenvectors of A^TA and square root of the non-zero singular values of A are the eigenvalues of A^TA
L,V=np.linalg.eig(np.matmul(np.transpose(A),A))

print(f'eighenvectors of A^TA:\n {V} \n')

print(f'square root of nonzero eigenvalues of A^TT:\n {np.sqrt(L)} \n')

eighenvectors of A^TA:
 [[-0.07687133  0.94764947 -0.30992142]
 [ 0.7885485   0.24800729  0.56274652]
 [-0.61014922  0.201129    0.76633221]] 

square root of nonzero eigenvalues of A^TT:
 [2.24727879e+00 7.53942020e-01 2.19865872e-08] 

